version: "3.8"
services:

  api:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 api:app
    env_file: .env
    expose:
      - "8080"
    deploy:
      replicas: 1

  limiter:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 sliding-window-limiter:app
    env_file: .env
    expose:
      - "8080"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 100M

  generator:
    build: .
    depends_on:
      - limiter
      - api
    command: python3 ./load-generator.py
    env_file: .env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 500M

  request-store:
    image: redis:alpine
    deploy:
      replicas: 1
    ports:
      - "6379:6379"
